# Generated by cucumber-sinatra. (2014-11-26 14:48:49 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/supermarket.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Supermarket

class SupermarketWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  SupermarketWorld.new
end
